version: '3'
services:
  app:
    image: ece3073-helpq
    ports:
      - "80:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/my-meteor-db
      - ROOT_URL=${ROOT_URL:-http://localhost:3000}
      - PORT=3000
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

